site_name: Mostafa Negim
site_url: "https://negim.ir"
site_author: Mostafa Negim
# repo_url: https://github.com/monegim
# nav:
#   - Home: 'index.md'
# markdown_extensions:
#   - toc:
#     permalink: "#"
# theme:
#   name: material
#   features:
#     - navigation.expand
#     - navigation.top
#     - content.code.copy
#   palette:
#     # Palette toggle for light mode
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       toggle:
#         icon: material/brightness-5
#         name: Switch to dark mode
#     # Palette toggle for dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       toggle:
#         icon: material/brightness-3
#         name: Switch to light mode
# extra_javascript: 
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
# markdown_extensions:
#   - mdx_math
#   - admonition
#   - sane_lists
#   - pymdownx.highlight:
#       auto_title: false
#   - pymdownx.superfences
#   - pymdownx.keys
docs_dir: src
# edit_uri: edit/main/src/
site_dir: docs

# use_directory_urls: false