site_name: Mostafa Negim
site_url: ""
site_author: Mostafa Negim
# repo_url: https://github.com/monegim
# nav:
#   - Home: 'index.md'

# Plugins
plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
theme: 
  name: material 
  #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate 
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
# extra_javascript: 
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - codehilite:
      linenums: true
      guess_lang: false
  - pymdownx.emoji
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - footnotes
  - toc:
      permalink: true
docs_dir: src
# edit_uri: edit/main/src/
site_dir: docs

# use_directory_urls: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/monegim
    - icon: fontawesome/brands/stackoverflow
      link: https://stackoverflow.com/users/10059628/andromeda
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mostafa-negim